version: "3.9" # optional since v1.27.0
services:
  postgres:
    container_name: postgres_container
    # network_mode: "host"
    networks:
      - web_crawler_network
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=DistributedWebCrawler
    ports:
      - 5432:5432
    volumes:
      - ~/docker-conf/postgresql/data/:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    # network_mode: "host"
    networks:
      - web_crawler_network
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/docker-conf/rabbitmq/log/:/var/log/rabbitmq

  # LOCK_SERVER --------------------------------------------------
  lock_server:
    # network_mode: "host"
    networks:
      - web_crawler_network
    depends_on:
      - postgres
    environment:
      - MY_PORT=9999
      - MY_HOST=lock_server
      - DB_PORT=5432
      - DB_HOST=postgres
    ports:
      - 9999:9999
    build:
      #    network: host
      context: ./
      dockerfile: ./Server/LockServer/Dockerfile

  # CLUSTER 1  ---------------------------------------------------
  master1:
    # network_mode: "host"
    networks:
      - web_crawler_network
    depends_on:
      - rabbitmq
      - lock_server
    environment:
      - MY_PORT=7777
      - MY_HOST=master1
      - LOCK_SERVER_PORT=9999
      - LOCK_SERVER_HOST=lock_server
      - MQ_HOST=rabbitmq
    ports:
      - 7777:7777
    build:
      #    network: host
      context: ./
      dockerfile: ./Server/cluster/master/Dockerfile

  worker11:
    # network_mode: "host"
    networks:
      - web_crawler_network
    depends_on:
      - master1
    environment:
      - MASTER_PORT=7777
      - MASTER_HOST=master1
    build:
      #    network: host
      context: ./
      dockerfile: ./Server/cluster/worker/Dockerfile

  worker12:
    # network_mode: "host"
    networks:
      - web_crawler_network
    depends_on:
      - master1
    environment:
      - MASTER_PORT=7777
      - MASTER_HOST=master1
    build:
      #    network: host
      context: ./
      dockerfile: ./Server/cluster/worker/Dockerfile

  worker13:
    # network_mode: "host"
    networks:
      - web_crawler_network
    depends_on:
      - master1
    environment:
      - MASTER_PORT=7777
      - MASTER_HOST=master1

    build:
      #    network: host
      context: ./
      dockerfile: ./Server/cluster/worker/Dockerfile
networks:
  web_crawler_network:
    driver: bridge
