version: "3.9" # optional since v1.27.0
services:
  database:
    container_name: database
    network_mode: "host"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=DistributedWebCrawler
    # ports:
    #   - 5432:5432
    volumes:
      - ~/docker-conf/postgresql/data/:/var/lib/postgresql/data 

  rabbitmq:
    image: rabbitmq:3-management-alpine
    network_mode: "host"
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    volumes:
      - ~/docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/docker-conf/rabbitmq/log/:/var/log/rabbitmq

  # CLUSTER 1  ---------------------------------------------------
  master:
    network_mode: "host"
    environment:
      - PORT=7777
    build:
      #    network: host
      context: ./
      dockerfile: ./cluster/master/Dockerfile

  worker1:
    network_mode: "host"
    environment:
      - PORT=7777
    build:
      #    network: host
      context: ./
      dockerfile: ./cluster/worker/Dockerfile

  worker2:
    network_mode: "host"
    environment:
      - PORT=7777
    build:
      #    network: host
      context: ./
      dockerfile: ./cluster/worker/Dockerfile

  worker3:
    network_mode: "host"
    environment:
      - PORT=7777
    build:
      #    network: host
      context: ./
      dockerfile: ./cluster/worker/Dockerfile
